# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
stages:
- stage: Build

  jobs:
  - job: buildandtest
  pool:
    vmImage: 'ubuntu-16.04'
    steps:
    - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
- stage: NotArtifactNowDelay

# Delay
# Delay further execution of a workflow by a fixed time
  jobs:
  - job: NotArtifactNowDelay
  pool:
    vmImage: 'ubuntu-16.04'
    steps:
    - task: Delay@1
      inputs:
      delayForMinutes: '1' 
  - job: Apologise
    pool:
      vmImage: 'ubuntu-16.04'
      steps:
    - task: Bash@3
      targetType: 'inline'
    script: echo Sorry for not getting the right stages in place on time


- stage: Test

  jobs:
  - job: Test
  pool:
    vmImage: 'ubuntu-16.04'
    steps:
    - task: Bash@3
      targetType: 'inline'
    script: echo Multi-stage pipeline
